{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jazzavatar.serviceAccountName" . }}
  labels:
{{ include "jazzavatar.labels" . | nindent 4 }}
{{- end -}}
