{{- if .Values.customEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
data:
{{- include "common.tplvalues.render" (dict "value" .Values.customEnv "context" $) | nindent 2 }}
{{- end }}